import OpenAI from "openai";
import type { ChatCompletionMessageParam } from "openai/resources/index.mjs";
import { OpenAITool } from "../services/mcp.js";
import { config } from "../config.js";

// Initialize isolated OpenAI client pointing to OpenRouter
const ai = new OpenAI({
    baseURL: "https://openrouter.ai/api/v1",
    apiKey: config.OPENROUTER_API_KEY || config.OPENAI_API_KEY || "",
    defaultHeaders: {
        "HTTP-Referer": "https://github.com/gravity-claw",
        "X-Title": "Gravity Claw AI - SubAgent",
    }
});

export const swarmDeclaration: OpenAITool = {
    type: "function",
    function: {
        name: "delegate_to_subagent",
        description: "Spin up a specialized sub-agent to handle a complex, parallel, or deep-reasoning task. Keeps the primary context window clean. The sub-agent is stateless and has no external native tools or SQLite memory.",
        parameters: {
            type: "object",
            properties: {
                role_description: {
                    type: "string",
                    description: "The system prompt/persona for the sub-agent. E.g., 'You are an expert Python debugger. Analyze this traceback.'"
                },
                task: {
                    type: "string",
                    description: "The specific objective or raw data the sub-agent needs to process."
                },
                model: {
                    type: "string",
                    description: "Optional model ID (e.g., 'google/gemini-2.5-pro' or 'anthropic/claude-3-haiku'). If omitted, defaults to google/gemini-2.5-pro."
                }
            },
            required: ["role_description", "task"]
        }
    }
};

export async function executeSwarmDelegation(args: any): Promise<any> {
    const targetModel = args.model || "google/gemini-2.5-pro";
    console.log(`[Swarm] 🐝 Spawning Sub-Agent (${targetModel})...`);
    console.log(`[Swarm] Role: ${args.role_description}`);

    try {
        const conversationHistory: ChatCompletionMessageParam[] = [
            { role: "system", content: args.role_description },
            { role: "user", content: args.task }
        ];

        const response = await ai.chat.completions.create({
            model: targetModel,
            messages: conversationHistory
        });

        const finalAns = response.choices[0]?.message?.content || "No response generated by sub-agent.";
        console.log(`[Swarm] 🐝 Sub-Agent returned: ${finalAns.substring(0, 50)}...`);

        return { result: finalAns };
    } catch (error: any) {
        console.error("[Swarm] Sub-Agent Execution failed:", error);
        return { error: `Sub-agent failed to process task: ${error.message}` };
    }
}
